
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: flask_test
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask:
    build: .
    environment:
      POSTGRE_URI: postgresql://postgres:1234@db:5432/flask_test
    volumes:
      - static_volume:/app/app/static
    expose:
      - 5000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "flask db upgrade&&gunicorn --bind 0.0.0.0:5000 run:app"

  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/app/app/static
    ports:
      - 1337:80
    depends_on:
      - flask

volumes:
  static_volume:
  postgres_data:
    external: true
