
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: flask_test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask:
    build: .
    environment:
      POSTGRE_URI: postgresql://postgres:1234@db:5432/flask_test
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "flask db upgrade&&python run.py"
